FROM node:14.17.6

# Set the working directory inside the container
WORKDIR /usr/src/front

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all files from the current directory to the working directory
COPY . .

RUN npm run build

# Specify the port number the container should expose
EXPOSE 3000

# Define the command to run your app
CMD [ "npm", "start" ]
