version: '3.1'

services:
  mongodb:
    image: mongo
    container_name: mp-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
 
  backend:
    container_name: moneypipe-backend
    build:
      context: backend/
      dockerfile: dockerfile
    env_file:
      - backend/.env
    volumes:
      - ./backend:/usr/src/back
    ports:
      - 3030:3030
    networks:
      - moneypipe
networks:
  moneypipe:

